{
  "event_id": "a968a7f1f494452f96e8be1a017d81ec",
  "project": 3,
  "release": null,
  "dist": null,
  "platform": "python",
  "message": "Here is a new error",
  "datetime": "2022-10-11T15:18:38.363000Z",
  "time_spent": null,
  "tags": [
    ["browser", "Firefox 105.0"],
    ["browser.name", "Firefox"],
    ["level", "info"],
    ["os.name", "Ubuntu"],
    ["runtime", "CPython 3.9.9"],
    ["runtime.name", "CPython"],
    ["server_name", "b25ba1d08e79"],
    ["transaction", "/message/Z"],
    ["url", "http://localhost:8001/message/"]
  ],
  "contexts": {
    "runtime": {
      "version": "3.9.9",
      "type": "runtime",
      "name": "CPython",
      "build": "3.9.9 (main, Dec 21 2021, 10:14:07) \n[GCC 10.2.1 20210110]"
    },
    "os": { "version": null, "name": "Ubuntu" },
    "trace": {
      "description": "message",
      "parent_span_id": "a1102070ade944af",
      "trace_id": "e5cfa4061b63408c8ffdcf918704e357",
      "op": "django.view",
      "type": "trace",
      "span_id": "aebc3c0e76dc7c6e"
    },
    "browser": { "version": "105.0", "name": "Firefox" }
  },
  "culprit": "/message/Z",
  "extra": { "sys.argv": ["./manage.py", "runserver", "0.0.0.0:8001"] },
  "fingerprint": ["{{ default }}"],
  "grouping_config": { "id": "legacy:2019-03-12" },
  "hashes": ["6585c6be473d334e97c29a955f843790"],
  "key_id": "3",
  "level": "info",
  "location": null,
  "logentry": {
    "message": "Here is a new {foo}",
    "params": { "foo": "error" },
    "formatted": "Here is a new error"
  },
  "logger": "",
  "metadata": { "title": "Here is a new error" },
  "modules": {
    "more-itertools": "8.14.0",
    "platformdirs": "2.5.2",
    "cffi": "1.15.1",
    "ipython-genutils": "0.2.0",
    "packaging": "21.3",
    "pygments": "2.13.0",
    "cleo": "1.0.0a5",
    "pip": "21.2.4",
    "prompt-toolkit": "3.0.3",
    "parso": "0.7.1",
    "jeepney": "0.8.0",
    "html5lib": "1.1",
    "appdirs": "1.4.4",
    "requests-toolbelt": "0.9.1",
    "regex": "2022.9.13",
    "sqlparse": "0.4.3",
    "distlib": "0.3.6",
    "msgpack": "1.0.4",
    "crashtest": "0.3.1",
    "sentry-sdk": "0.19.5",
    "ipdb": "0.12.3",
    "six": "1.16.0",
    "poetry": "1.2.1",
    "ptyprocess": "0.7.0",
    "click": "8.0.4",
    "importlib-metadata": "4.12.0",
    "jedi": "0.17.2",
    "traitlets": "4.3.3",
    "asgiref": "3.4.1",
    "charset-normalizer": "2.1.1",
    "cachy": "0.3.0",
    "pathspec": "0.9.0",
    "cachecontrol": "0.12.11",
    "certifi": "2022.9.24",
    "wheel": "0.37.0",
    "backcall": "0.2.0",
    "jsonschema": "4.16.0",
    "cryptography": "38.0.1",
    "pycparser": "2.21",
    "secretstorage": "3.3.3",
    "urllib3": "1.26.12",
    "virtualenv": "20.16.5",
    "webencodings": "0.5.1",
    "poetry-plugin-export": "1.0.7",
    "pytz": "2022.2.1",
    "ipython": "7.16.3",
    "pexpect": "4.8.0",
    "jaraco.classes": "3.2.3",
    "zipp": "3.8.1",
    "pickleshare": "0.7.5",
    "decorator": "5.1.1",
    "filelock": "3.8.0",
    "dulwich": "0.20.46",
    "lockfile": "0.12.2",
    "typed-ast": "1.5.4",
    "keyring": "23.9.3",
    "wcwidth": "0.2.5",
    "django": "3.2.15",
    "poetry-core": "1.2.0",
    "pyrsistent": "0.18.1",
    "pyparsing": "3.0.9",
    "pylev": "1.4.0",
    "toml": "0.10.2",
    "setuptools": "59.6.0",
    "pkginfo": "1.8.3",
    "black": "19.10b0",
    "requests": "2.28.1",
    "shellingham": "1.5.0",
    "idna": "3.4",
    "tomlkit": "0.11.5",
    "attrs": "22.1.0"
  },
  "received": 1665501518.528,
  "request": {
    "url": "http://localhost:8001/message/",
    "headers": [
      [
        "Accept",
        "text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,*/*;q=0.8"
      ],
      ["Accept-Encoding", "gzip, deflate, br"],
      ["Accept-Language", "en-US,en;q=0.5"],
      ["Connection", "keep-alive"],
      ["Content-Length", ""],
      ["Content-Type", "text/plain"],
      ["Host", "localhost:8001"],
      ["Referer", "http://localhost:8001/"],
      ["Sec-Fetch-Dest", "document"],
      ["Sec-Fetch-Mode", "navigate"],
      ["Sec-Fetch-Site", "same-origin"],
      ["Sec-Fetch-User", "?1"],
      ["Upgrade-Insecure-Requests", "1"],
      [
        "User-Agent",
        "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:105.0) Gecko/20100101 Firefox/105.0"
      ]
    ],
    "method": "GET",
    "env": { "SERVER_NAME": "b25ba1d08e79", "SERVER_PORT": "8001" },
    "inferred_content_type": "text/plain"
  },
  "sdk": {
    "version": "0.19.5",
    "name": "sentry.python",
    "packages": [{ "version": "0.19.5", "name": "pypi:sentry-sdk" }],
    "integrations": [
      "argv",
      "atexit",
      "dedupe",
      "django",
      "excepthook",
      "logging",
      "modules",
      "stdlib",
      "threading"
    ]
  },
  "timestamp": 1665501518.363,
  "title": "Here is a new error",
  "transaction": "/message/Z",
  "type": "default",
  "use_rust_normalize": true,
  "version": "7"
}
